name: 'test'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    name: Lint, Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '20']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - run: pnpm install --frozen-lockfile
      # -------------- end of setup

      - name: Lint source
        run: |
          pnpm run lint:ci

      - name: Build apps and packages
        run: |
          pnpm run build:ci

      - name: Run tests
        run: |
          pnpm run test:ci
        env:
          CI: true
